---
- name:	Upload configs
  hosts: PC
  become: yes

  tasks:
  - name: Download DomainGUI.sh
     get_url:
      url: https://github.com/otretsoff/ansible/blob/main/Configs/DomainGUI.sh
      dest: /home/DomainGUI.sh
      remote_src: yes
      mode: '777'
