---
- name:	Upload configs
  hosts: PC
  become: true
  tasks:
  - name: Create TMP
    become: true
    file:
      path: /tmp/.ansible
      state: directory
      mode: 0755
  - name: Download DomainGUI.sh
    become: true
    become_user: otretsovaa@main.ru
    become_method: sudo
    get_url:
      url: http://repo.main.ru/redos/7.3/x86_64/setup/DomainGUI.sh
      dest: /home/DomainGUI.sh
      force: true
