---
- name:	Upload configs
  hosts: CBDO
  become: true
  tasks:
  - name: Create TMP
    become: true
    file:
      path: /tmp/.ansible
      state: directory
      mode: 0755
      
  - name: Download DomainGUI1.sh
    become: true
    become_method: sudo
    get_url:
      url: https://github.com/otretsoff/ansible/blob/main/Configs/DomainGUI.sh
      dest: /home/
      mode: 0777
      group: root
      owner: root
