---
- name:	Upload configs
  hosts: NEW
  become: true
  tasks:
  - name: Create TMP
    become: true
    file:
      path: /tmp/.ansible
      state: directory
      mode: 0755
  
  - name: Download DomainGUI.sh
    become: true
    get_url:
      url: https://github.com/otretsoff/ansible/blob/main/Configs/DomainGUI.sh
      dest: /home/DomainGUI.sh
      force: true
      group: root
      owner: root
      mode: g=rwx
      
