---
- name:	Upload configs
  hosts: CBDO
  become: yes
  tasks:
  - name: Create TMP
    become: yes
    file:
      path: /tmp/.ansible
      state: directory
      mode: 0755
      
  - name: Download DomainGUI.sh
    become: yes
    get_url:
      url: https://github.com/otretsoff/ansible/blob/main/Configs/DomainGUI.sh
      dest: /home/DomainGUI.sh
      mode: 0755
      checksum: 68848affc1ee836487e15269341de3dffbf990bb
      group: root
      owner: root
