---
- name:	Upload configs
  hosts: PC
  become: yes

  tasks:
  - name: Copy configurations files
    ansible.builtin.copy: 
      src: https://github.com/otretsoff/ansible/blob/main/Configs/DomainGUI.sh
      dest: /home/DomainGUI.sh
      remote_src: yes
      mode: '777'
